#    Here functionality is  provided for all of the buttons in the lower
#    left corner of the canvas. These buttons deal with managing data
#    after it has been collected. Copying data, deleteing data...
